version: '3'
services:
  geojsonconverter:
    restart: always
    image: usdotjpoode/geojsonconverter:release_1.2.0
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      geometry.output.mode: ${GEOMETRY_OUTPUT_MODE}
      spring.kafka.bootstrap-servers: ${DOCKER_HOST_IP}:9092
    logging: 
      options:
        max-size: "10m"
        max-file: "5"
